### ISSUE TITLE
[Announcement] Branching

### ISSUE THREAD

**Issue by martinbeentjes** [martinbeentjes/npm-get-version-action#23]
I have cause quite some issues around repositories by changing branch names and adding jq. 

Both branches master and main now exist for a period before I completely switch to main.

**Comment by connorlurring** [comment]
@martinbeentjes to inform people to switch over, the `warning` method from https://github.com/actions/toolkit/tree/main/packages/core#annotations could be added to the `master` branch to surface a message informing the users to switch the referenced branch to main. This should help prevent a repeat of the previous change over, where builds started failing with no prior warning.

Additionally, the documentation could be changed to suggest using a pinned version via a tag rather than a branch as the `@` reference. This would also mean that any changes in the future that are not backwards compatible would not break pipelines.
